### PR TITLE
Tail-call lowering: keep loop-carried values alive, and align mutual-trampoline equality

### LINKED ISSUE #1105: Rust backend at 9d4131de: tail-call-lowered functions move a carried parameter, and == between a temporary and a parameter misses a deref
## What we are building

n1bor/btc-listener, moving its pin from ea1bfa56 to 9d4131de to take #1099 and #1104. `aver check` and `aver verify` pass (6,277 cases, in 19 s — thank you); `aver compile` then produces Rust that does not build: **7 errors in 6 modules**, every one in a tail-call-lowered function, none of which changed since the last pin. At ea1bfa56 the same sources compiled and ran a 400,000-Block audit.

## Two shapes, reduced to 40 lines

```aver
module Main
    intent =
        "Reproducer: two tail-call shapes the Rust backend at 9d4131de no longer"
        "lowers to code that compiles."
    exposes [main]
    depends []
    effects [Console.print]

fn tagged(tag: String, items: List<Int>, index: Int, acc: List<String>) -> List<String>
    ? "A parameter that is both carried into the self tail call and used in it."
    match items
        [] -> acc
        [head, ..tail] -> tagged(tag, tail, index + 1, List.prepend(label(tag, index, head), acc))

verify tagged
    tagged("t", [7, 8], 0, []) => ["t:1:8", "t:0:7"]

fn label(tag: String, index: Int, head: Int) -> String
    ? "The carried parameters, used."
    "{tag}:{index}:{head}"

verify label
    label("t", 0, 7) => "t:0:7"

fn without(items: List<List<Int>>, target: List<Int>, acc: List<List<Int>>) -> List<List<Int>>
    ? "Mutual tail recursion whose partner compares a computed list to a parameter."
    match items
        [] -> List.reverse(acc)
        [head, ..tail] -> kept(head, tail, target, acc)

verify without
    without([[1], [2]], [1], []) => [[2]]

fn kept(item: List<Int>, rest: List<List<Int>>, target: List<Int>, acc: List<List<Int>>) -> List<List<Int>>
    ? "An owned temporary on the left of ==, a parameter on the right."
    match List.reverse(item) == target
        true -> without(rest, target, acc)
        false -> without(rest, target, List.prepend(item, acc))

verify kept
    kept([1], [], [1], []) => []

fn main() -> Unit
    ? "Print both results."
    ! [Console.print]
    _a = Console.print(String.join(tagged("t", [7, 8], 0, []), ","))
    Console.print("{List.len(without([[1], [2]], [1], []))}")
```

`aver verify main.av` → 4/4. `aver compile main.av -o out && cd out && cargo build` →

```
error[E0308]: mismatched types
  --> src/aver_generated/entry/mod.rs:19:39
19 | ...   if (item.reverse() == target) { __MutualTco1::Without(rest, acc) } else { ...
   |           --------------    ^^^^^^ expected `AverIntList`, found `&AverIntList`

error[E0382]: use of moved value: `tag`
  --> src/aver_generated/entry/mod.rs:43:59
37 | pub fn tagged(mut tag: AverStr, mut items: aver_rt::AverIntList, mut index: aver_rt::AverInt, mut acc: ...
   |               ------- move occurs because `tag` has type `aver_rt::AverStr`, which does not implement the `Copy` trait
38 |     loop {
   |     ---- inside of this loop
```

1. **A carried parameter, used.** A self tail call that passes `tag` through unchanged *and* hands it to another function in the same arm. The loop lowering moves `tag` into the call and then needs it again on the next iteration; the old backend cloned, the new one does not. In btc-listener this is `infra/outputs.av entriesFor` (`txid`), `infra/txindex.av sitesFor` (`blockId`), `domain/inventory.av entriesFor` (`kind`), `domain/bech32.av checksumDigits` (`residue`), `domain/scriptwork.av spreadOver` (`position`, `weight`) — Strings and Ints alike.
2. **An owned temporary compared to a parameter.** In a mutual-recursion group, `List.reverse(item) == target` lowers to `item.reverse() == target` where `target` is `&AverIntList`; rustc wants `*target`. In btc-listener: `domain/scriptparse.av keptUnlessMatched`, which is FindAndDelete.

Bisecting by eye, cedafe0b (#1098, "finish resolved-IR migration and remove AST/codegen bridges") or 2e009dd7 (#1091, "consume resolved functions in codegen") are the candidates; I have not built the intermediate commits.

## What we are not asking for

Not asking for the loop lowering to change shape — the tail-call-to-loop is what keeps a 400,000-iteration walk off the stack, and the clone it used to insert is the right price. Only that it compile again.

### PR DESCRIPTION
**Pull request by jasisz**
Fixes #1105. Two shapes, two separate causes, both reported against 9d4131de by n1bor/btc-listener, whose sources had not changed since the previous pin.

Regression introduced by cedafe0b (#1098, the resolved-IR migration), found by bisect with an independent rebuild of the good and bad commits rather than by reading the diff.

## Shape 1 — a loop-carried parameter was moved

```aver
fn entriesFor(txid: String, items: List<Int>, index: Int, acc: List<String>) -> List<String>
    match items
        [] -> List.reverse(acc)
        [head, ..tail] -> entriesFor(txid, tail, index + 1, List.prepend(entryFor(txid, index), acc))
```

Resolved pass-through detection elided the identity TCO argument for `txid`, so the last-use analysis let the helper call move it — not seeing the use hidden in the next lap of the loop. `error[E0382]: use of moved value`.

Loop-carried parameters are now tracked per tail call, and the existing ownership policy clones only at genuine owning uses. Identity pass-through, borrows and `Copy` values stay clone-free — a blanket clone here would be a silent performance regression on a hot path.

## Shape 2 — a mutual trampoline compared an owned temporary to a borrowed invariant

```aver
fn kept(item: List<Int>, rest: List<List<Int>>, target: List<Int>, acc: List<List<Int>>) -> …
    match List.reverse(item) == target
```

`error[E0308]: expected AverIntList, found &AverIntList`.

Worth recording, because it is the more interesting half: this is the **same class as #1037, #1060 and #1065, and it bypassed their fix entirely**. Mutual TCO does reach `mir_emit_equality`, but a trampoline's hoisted invariants live only in `rc_wrapped`, while the alignment logic added by those tickets consulted `borrowed_params` alone. Their tests covered ordinary borrowed parameters, never a mutual trampoline, so the gap was invisible.

Mutual trampoline contexts now classify `rc_wrapped` invariants as borrowed references for equality emission. The existing alignment then emits `&(item.reverse()) == target` — no allocation, no clone. Self-TCO's `Arc<T>` representation is untouched.

## Tests

Two regression tests in `tests/rust_codegen_differential.rs`, each red before its fix and green after. Both go further than asserting emitted text: they build the generated project and run its verify cases. The mutual test requires a `__MutualTco` trampoline in the output, because a self-recursive case never reaches that path — which is exactly how the earlier tickets missed this.

`cargo fmt --all -- --check`, `cargo clippy` and `cargo test --test rust_codegen_differential` (56 passed) all pass. Both reproducers from the issue compile and build end to end; verified independently of the implementer's report.

### CODE REVIEW

**Comment by n1bor** [comment]
So quick to fix! Thanks!

**Comment by jasisz** [comment]
Quick to break, quick to fix! To be honest I had some gut-feeling this may happen after some of the last PRs aligning MIR for Rust codegen. I should have checked on btc-listener myself ;)
I am slowly preparing for 0.,29 release, which will unfortunately include one more breaking change - I will mention you in there for sure.
